### ISSUE TITLE
"ascii' codec can't decode byte 0xe6 in position 49: ordinal not in range(128) 

### ISSUE THREAD

**Issue by xzy9565** [kevin-funderburg/alfred-microsoft-onenote-navigator#6]
Hi there,
I have some Chinese characters inside of my notebook. 
The section name in Chinese is fine. 
![image](https://user-images.githubusercontent.com/15137722/67493065-52923280-f645-11e9-9b0a-153720208c87.png)

However, when I go into this section, it'll show this error:
![image](https://user-images.githubusercontent.com/15137722/67492684-cbdd5580-f644-11e9-9098-43ae3581bc0d.png)

The pages inside this section have some Chinese titles as well as contents.

Is it possible to solve this issue?

**Comment by Adol1111** [comment]
set utf-8 at getNotebooks.py
```python
reload(sys)
sys.setdefaultencoding('utf-8')
```

**Comment by xzy9565** [comment]
Thanks for your solution.
Problem solved.
