### ISSUE TITLE
can this search all pages and subpages from the start? Without requiring the user to navigate to what he needs

### ISSUE THREAD

**Issue by pedrocatre** [kevin-funderburg/alfred-microsoft-onenote-navigator#7]
Seems like this would be most useful by allowing us to search and navigate to any page or subpage in onenote directly. It appears we are currently forced to navigate inside a notebook first before we can search for pages.

Is that the case? Is that by design? Why this choice? It seems to make the entire navigation much slower that we have to chose the notebook first. And also that we can't just search for subpages.

**Comment by kevin-funderburg** [comment]
You know I honestly hadn’t considered that! It seems doable, it would have to be re-worked (obviously) but I’ll take a look at that soon 😁

**Comment by pedrocatre** [comment]
good :) 👍 in my mind it would be perfect it this behaved similarly to how searching and navigation of files works on intellij https://www.jetbrains.com/help/idea/searching-everywhere.html

**Comment by kevin-funderburg** [comment]
i just added the ability to search all notebooks/section groups/sections, totally inspired by @pedrocatre 

I will add to this soon so that you can select the result and if it has sub sections it will allow you to browse it rather than just open the selection in OneNote, but I wanted to get this up for now

**Comment by kevin-funderburg** [comment]
just pushed the newest version which allows to search and browse more fluidly, hope you like!
