### ISSUE TITLE
a suggestion

### ISSUE THREAD

**Issue by liushawulan** [kevin-funderburg/alfred-microsoft-onenote-navigator#9]
plz condiser to add a page-searching option. it'll be much efficient than before. 
now the workflow only allow me to open  the sub-section, not the pages whthin it. 
![image](https://user-images.githubusercontent.com/38710354/75303485-d2dad580-587b-11ea-997f-e51573574c64.png)
![image](https://user-images.githubusercontent.com/38710354/75303683-66140b00-587c-11ea-9283-381684e69673.png)
![image](https://user-images.githubusercontent.com/38710354/75303765-99ef3080-587c-11ea-8df8-c65597ac8fa9.png)

sorry i don't know how much efforts will be involved in this idea. 
I appreciate your consideration.

**Comment by kevin-funderburg** [comment]
unfortunately, searching pages isn't possible. This workflow uses a plist provided by microsoft to build the results, and that plist only contains notebooks, sections, and section groups. So if i could i definitely would, but until the pages are provided, it's not possible.
